import { Neomatrix } from "neomatrix.slint";
import { Node, NodeData } from "node.slint";

export component MainWindow inherits Window {
    background: #000000;



    callback update(int, int);


    in property <[NodeData]> nodes: [
        {active: false, row_index: 0, col_index: 0,},
        {active: false, row_index: 1, col_index: 0,},
        {active: false, row_index: 2, col_index: 0,},
        {active: false, row_index: 3, col_index: 0,},
        {active: false, row_index: 4, col_index: 0,},
        {active: false, row_index: 0, col_index: 1,},
        {active: false, row_index: 1, col_index: 1,},
        {active: false, row_index: 2, col_index: 1,},
        {active: false, row_index: 3, col_index: 1,},
        {active: false, row_index: 4, col_index: 1,},
        {active: false, row_index: 0, col_index: 2,},
        {active: false, row_index: 1, col_index: 2,},
        {active: false, row_index: 2, col_index: 2,},
        {active: false, row_index: 3, col_index: 2,},
        {active: false, row_index: 4, col_index: 2,},
];

    in property <int> row_count: 5;
    in property <[string]> rows:[
        "row_1", "row_2", "row_3","row_4","row_5"
     ];

    in property <int> col_count: 3;
    in property <[string]> columns:[
       "col_1", "col_2", "col_3"
    ];


    neo := Neomatrix{
        row-count: row-count;
        col-count: col-count;
        rows: rows;
        columns: columns;
        nodes: nodes;
    }


   
}





